version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ~/Desktop/stickers/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_MULTIPLE_DATABASES=sticker,sticker_test
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080

